### ISSUE TITLE
Migrate to NullSafety

### ISSUE THREAD

**Issue by pythonhubdev** [gbmiranda/flutter_plus#4]
Please migrate to null safety.

**Comment by pythonhubdev** [comment]
I have migrated the codebase to complete the null safe version and I have also made a pr for it. You can review and accept the pr. @renatoassis01 @gbmiranda

**Comment by renatoassis01** [comment]
@pythonhubpy Amazing. Gabriel will review

**Comment by pythonhubdev** [comment]
Thanks will work on other todo's.

**Comment by pythonhubdev** [comment]
Migrated to null Safety #5
